"use strict";
const vscode=require("vscode"),fs=require("fs"),path=require("path");
const {checkProject,buildPackage}=require("./src/project");
const {templateProviders}=require("./src/extensions");
const workspaceRoot=()=>vscode.workspace.workspaceFolders?.[0]?.uri.fsPath||"";
function projectRoot(){const root=workspaceRoot();if(!root)return "";const nested=path.join(root,"Goodecode");return fs.existsSync(path.join(root,"goodecode.toml"))?root:fs.existsSync(path.join(nested,"goodecode.toml"))?nested:root;}
async function createProject(){const root=workspaceRoot();if(!root)return vscode.window.showWarningMessage("Open a folder before creating a Goodecode project.");const main=path.join(root,"src/main.goode.py"),name=path.basename(root).replaceAll('"',"");if(fs.existsSync(main))return vscode.window.showInformationMessage("This folder already contains src/main.goode.py.");const template=templateProviders()[0].create(name);for(const [relative,contents] of Object.entries({"goodecode.toml":template.manifest,...template.files})){const target=path.join(root,relative);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,contents);}await vscode.window.showTextDocument(vscode.Uri.file(main));}
async function check(){const root=projectRoot();if(!root)return vscode.window.showWarningMessage("Open a Goodecode project first.");const result=checkProject(root);if(result.errors.length)return vscode.window.showErrorMessage(`Goodecode authoring checks failed:\n${result.errors.join("\n")}`);return vscode.window.showInformationMessage(`Goodecode project is structurally ready to export.${result.warnings.length?` ${result.warnings.join(" ")}`:""}`);}
async function exportForGoodebot(context){const root=projectRoot();if(!root)return vscode.window.showWarningMessage("Open a Goodecode project first.");const target=path.join(root,`${path.basename(root).replace(/[^A-Za-z0-9._-]+/g,"-")||"Goodecode-Project"}.goode`);try{buildPackage({root,outputPath:target,extensionVersion:context.extension.packageJSON.version});}catch(error){return vscode.window.showErrorMessage(`Goodecode export blocked:\n${error.message}`);}const action=await vscode.window.showInformationMessage(`Exported ${path.basename(target)} for Goodebot. Runtime and deployment checks happen after import.`,"Reveal");if(action==="Reveal")await vscode.commands.executeCommand("revealFileInOS",vscode.Uri.file(target));}
function activate(context){context.subscriptions.push(vscode.commands.registerCommand("goodecode.openStudio",check),vscode.commands.registerCommand("goodecode.refreshSidebar",check),vscode.commands.registerCommand("goodecode.openGoodebotDownload",()=>vscode.env.openExternal(vscode.Uri.parse("https://goodebot.net/download"))),vscode.commands.registerCommand("goodecode.openWorkspaceFolder",()=>vscode.commands.executeCommand("revealFileInOS",vscode.Uri.file(workspaceRoot()))),vscode.commands.registerCommand("goodecode.createStarterFiles",createProject),vscode.commands.registerCommand("goodecode.createSingleScriptTemplate",createProject),vscode.commands.registerCommand("goodecode.migrateTemplateV2",createProject),vscode.commands.registerCommand("goodecode.openSyntaxGuidePreview",()=>vscode.commands.executeCommand("markdown.showPreview",vscode.Uri.file(path.join(context.extensionPath,"content/goodecode-syntax-guide.md")))),vscode.commands.registerCommand("goodecode.checkProject",check),vscode.commands.registerCommand("goodecode.exportGoodeFile",()=>exportForGoodebot(context)));}
function deactivate(){}
module.exports={activate,deactivate};
